export const MyFonts = {
  fontPoppinsR: 'Poppins-Regular',
  fontPoppinsB: 'Poppins-Bold',
  fontQuickB: 'Quicksand-Bold',
  fontQuickR: 'Quicksand-Regular',
  fontRalewayR: 'Raleway-Regular',
  fontRalewayB: 'Raleway-Bold',
  black: 'Roboto-Black',
  blackItalic: 'Roboto-BlackItalic',
  bold: 'Roboto-Bold',
  boldItalic: 'Roboto-BoldItalic',
  light: 'Roboto-Light',
  medium: 'Roboto-Medium',
  regular: 'Roboto-Regular',
  thin: 'Roboto-Thin',
};
