export const Routes = {
  SPLASH: 'Splash Screen',
  SINGIN: 'Sign In',
  VERIFICATION: 'Verification',
  CONTACTS: 'Contacts',
  MESSAGE: 'Message',
  CALLS: 'Calls',
  CHATS: 'Chats',
  CHATBOX: 'Chat Box',
  SENDCHAT: 'SendChat',
  PROFIL: 'Profile',
  PROFILEDIT: 'Profile edit',
  CONTACTADD: 'Contact Add',
  TAB: 'Menu',
  HOME: 'Anasayfa',
  INTRO: 'Intro',
  USER: 'Profile',
  CONTACTDETAIL: 'Contact Detail',
  USERCHAT: 'User Chat Screen',
  CHATADD: 'Chat Add List',
};
