export const actionType = {
  SAVE_DEVICE_ID: 'SAVE_DEVICE_ID',
  FETCH_DEVICE_MYPHONE_NUMBER: 'FETCH_DEVICE_MYPHONE_NUMBER',
  FETCH_USERLIST_FIREBASE: 'FETCH_USERLIST_FIREBASE ',
  FETCH_WIFI_CONNECT: 'FETCH_WIFI_CONNECT ',
  FETCH_DEVICE_MYINFO: 'FETCH_DEVICE_MYINFO ',
  FETCH_CONTACTS_LIST: 'FETCH_CONTACTS_LIST',
  FETCH_CHATS_LIST: 'FETCH_CHATS_LIST',
  SAVEDEVICEDATA: 'SAVEDEVICEDATA',
};
